name: "my hello action"

description: "say hello with GitHub Actions"

inputs:
  firstGreeting:
    description: "who would liek to greet in the console"
    required: true
    default: "Hubot"

  secondGreeting:
    description: "another person to greet"
    required: true
    default: "Monta the Octocat"

  thirdGreeting:
    description: "a third greeting"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
